// Generates the sound effects as tiny WAV files embedded in src/sounds.generated.ts.
// Run: npm run sounds
import { writeFileSync } from 'node:fs'

const RATE = 16000
const [C5, E5, G5, A5, C6, E6, G6] = [523.25, 659.25, 783.99, 880, 1046.5, 1318.5, 1568]

/** One note: linear 10ms attack, then exponential decay to silence (like a struck bell). */
function note(freq, start, dur, { gain = 1, type = 'sine', to } = {}) {
  return { freq, start, dur, gain, type, to }
}
const chime = (f, start, dur = 0.4, gain = 1) => [note(f, start, dur, { gain }), note(f * 2, start, dur * 0.6, { gain: gain * 0.4 })]

const wave = (type, phase) => (type === 'triangle' ? (2 / Math.PI) * Math.asin(Math.sin(phase)) : Math.sin(phase))

function render(notes, peak) {
  const total = Math.max(...notes.map((n) => n.start + n.dur)) + 0.05
  const out = new Float32Array(Math.ceil(total * RATE))
  for (const n of notes) {
    const first = Math.floor(n.start * RATE)
    const len = Math.floor(n.dur * RATE)
    let phase = 0
    for (let i = 0; i < len; i++) {
      const t = i / RATE
      const f = n.to ? n.freq * Math.pow(n.to / n.freq, t / n.dur) : n.freq
      phase += (2 * Math.PI * f) / RATE
      const attack = 0.01
      const env = t < attack ? t / attack : Math.pow(0.0001, (t - attack) / (n.dur - attack))
      out[first + i] += wave(n.type, phase) * env * n.gain
    }
  }
  const max = out.reduce((m, v) => Math.max(m, Math.abs(v)), 0) || 1
  return out.map((v) => (v / max) * peak)
}

function wav(samples) {
  const buf = Buffer.alloc(44 + samples.length * 2)
  buf.write('RIFF', 0); buf.writeUInt32LE(36 + samples.length * 2, 4); buf.write('WAVE', 8)
  buf.write('fmt ', 12); buf.writeUInt32LE(16, 16); buf.writeUInt16LE(1, 20); buf.writeUInt16LE(1, 22)
  buf.writeUInt32LE(RATE, 24); buf.writeUInt32LE(RATE * 2, 28); buf.writeUInt16LE(2, 32); buf.writeUInt16LE(16, 34)
  buf.write('data', 36); buf.writeUInt32LE(samples.length * 2, 40)
  samples.forEach((v, i) => buf.writeInt16LE(Math.round(Math.max(-1, Math.min(1, v)) * 32767), 44 + i * 2))
  return buf
}

const sounds = {
  tap: render([note(700, 0, 0.09, { to: 480 })], 0.6),
  key: render([note(980, 0, 0.06)], 0.45),
  correct: render([...chime(A5, 0, 0.3), ...chime(E6, 0.12, 0.55)], 0.9),
  wrong: render([note(260, 0, 0.18, { type: 'triangle' }), note(196, 0.15, 0.32, { type: 'triangle' })], 0.85),
  match: render(chime(G6, 0, 0.4), 0.8),
  complete: render(
    [...[C5, E5, G5, C6].flatMap((f, i) => chime(f, i * 0.12, 0.55)), ...chime(E6, 0.55, 0.9), ...chime(G6, 0.68, 1, 0.85)],
    0.9,
  ),
  fail: render([392, 349.23, 311.13, 261.63].map((f, i) => note(f, i * 0.18, 0.34, { type: 'triangle' })), 0.85),
}

const entries = Object.entries(sounds).map(([name, s]) => `  ${name}: 'data:audio/wav;base64,${wav(s).toString('base64')}',`)
writeFileSync(
  new URL('../src/sounds.generated.ts', import.meta.url),
  `// Generated by scripts/make-sounds.mjs – do not edit. Tiny 16 kHz mono WAV files as data URIs.\nexport const SOUNDS = {\n${entries.join('\n')}\n} as const\n`,
)
for (const [name, s] of Object.entries(sounds)) console.log(name.padEnd(9), (s.length / RATE).toFixed(2) + 's', 'peak', s.reduce((m, v) => Math.max(m, Math.abs(v)), 0).toFixed(2))
