/**
 * Sound effects (short WAVs generated by scripts/make-sounds.mjs).
 *
 * Playback goes through the Web Audio API: the clips are decoded once and then start immediately.
 * `<audio>` elements are the fallback – on iPhones they run through the media pipeline and start
 * half a second to a second after the tap, which is far too slow for button clicks.
 *
 * The catch is that Web Audio alone is silenced by an iPhone's ring/silent switch. Keeping one
 * silent `<audio>` loop playing puts the page in the "playback" audio session, where it is not.
 */
import { SOUNDS } from './sounds.generated'

type Name = keyof typeof SOUNDS
type WebkitWindow = typeof window & { webkitAudioContext?: typeof AudioContext }

let enabled = true
let ctx: AudioContext | null = null
let master: GainNode | null = null
const buffers = new Map<Name, AudioBuffer>()
const elements = new Map<Name, HTMLAudioElement>()
let keepAlive: HTMLAudioElement | null = null

export function setSoundEnabled(on: boolean): void {
  enabled = on
  if (!on) stopKeepAlive()
}

const bytesOf = (dataUri: string) => Uint8Array.from(atob(dataUri.split(',')[1]), (c) => c.charCodeAt(0))

/** A short, genuinely silent WAV – played on a loop only to hold the iOS audio session open. */
function silentWav(): string {
  const samples = 8000 // half a second at 16 kHz
  const buf = new Uint8Array(44 + samples * 2)
  const view = new DataView(buf.buffer)
  const ascii = (at: number, s: string) => [...s].forEach((c, i) => buf.set([c.charCodeAt(0)], at + i))
  ascii(0, 'RIFF'); view.setUint32(4, 36 + samples * 2, true); ascii(8, 'WAVEfmt ')
  view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true)
  view.setUint32(24, 16000, true); view.setUint32(28, 32000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true)
  ascii(36, 'data'); view.setUint32(40, samples * 2, true)
  let bin = ''
  buf.forEach((b) => (bin += String.fromCharCode(b)))
  return 'data:audio/wav;base64,' + btoa(bin)
}

function audio(): AudioContext | null {
  if (ctx) return ctx
  const Ctor = window.AudioContext ?? (window as WebkitWindow).webkitAudioContext
  if (!Ctor) return null
  ctx = new Ctor({ latencyHint: 'interactive' })
  master = ctx.createGain()
  master.connect(ctx.destination)
  // decode every clip once, so playing one later costs nothing
  for (const name of Object.keys(SOUNDS) as Name[]) {
    const bytes = bytesOf(SOUNDS[name])
    ctx.decodeAudioData(bytes.buffer.slice(0) as ArrayBuffer).then(
      (buf) => buffers.set(name, buf),
      () => {}, // fall back to the <audio> element for this clip
    )
  }
  return ctx
}

function element(name: Name): HTMLAudioElement {
  let a = elements.get(name)
  if (!a) {
    a = new Audio(SOUNDS[name])
    a.preload = 'auto'
    elements.set(name, a)
  }
  return a
}

function playElement(name: Name): Promise<boolean> {
  const a = element(name)
  a.muted = false
  try {
    a.currentTime = 0
  } catch {
    /* not loaded yet – it starts from the beginning anyway */
  }
  return (a.play() ?? Promise.resolve()).then(
    () => true,
    () => false,
  )
}

function play(name: Name): Promise<boolean> {
  if (!enabled) return Promise.resolve(false)
  const c = audio()
  const buf = buffers.get(name)
  if (c && buf) {
    // a context that is still waking up is fine: the clip is scheduled and plays the moment it resumes
    if (c.state !== 'running') void c.resume().catch(() => {})
    const src = c.createBufferSource()
    src.buffer = buf
    src.connect(master!)
    src.start()
    return Promise.resolve(true)
  }
  return playElement(name) // only before the clips finish decoding, or with no Web Audio at all
}

function startKeepAlive(): void {
  if (!enabled || (keepAlive && !keepAlive.paused)) return
  if (!keepAlive) {
    keepAlive = new Audio(silentWav())
    keepAlive.loop = true
    keepAlive.preload = 'auto'
  }
  keepAlive.play()?.catch(() => {})
}

function stopKeepAlive(): void {
  keepAlive?.pause()
}

/**
 * Browsers only start audio inside a real tap. Every gesture resumes the audio context and
 * (re)starts the silent loop, so the very next sound plays instantly and through the ring switch.
 */
function prime(): void {
  const c = audio()
  if (c && c.state !== 'running') void c.resume().catch(() => {})
  startKeepAlive()
}

export const sfx = {
  /** tap for any button */
  tap: () => void play('tap'),
  /** on-screen keyboard key */
  key: () => void play('key'),
  /** right answer: two rising chimes */
  correct: () => void play('correct'),
  /** wrong answer: two falling notes */
  wrong: () => void play('wrong'),
  /** a correct pair while matching */
  match: () => void play('match'),
  /** lesson complete: rising arpeggio with a sparkle */
  complete: () => void play('complete'),
  /** out of hearts */
  fail: () => void play('fail'),
}

/** Plays a sample sound and reports whether the browser allowed it (used by the "test sound" button). */
export function testSound(): Promise<boolean> {
  prime()
  return play('correct')
}

/** Anything a person would tap or click. Elements can opt out with data-silent (they make their own sound). */
const CLICKABLE =
  'button, a[href], label, summary, select, [role="button"], input[type="checkbox"], input[type="radio"], input[type="date"]'

/** Every tap/click in the app makes a sound. */
export function installClickSounds(): () => void {
  audio() // start decoding the clips now, so even the first tap is instant
  const onDown = (e: Event) => {
    prime()
    const el = (e.target as Element | null)?.closest?.<HTMLElement>(CLICKABLE)
    if (!el || (el as HTMLButtonElement).disabled || el.dataset.silent !== undefined) return
    if (el.classList.contains('kb-key')) sfx.key()
    else sfx.tap()
  }
  const onGesture = () => prime()
  document.addEventListener('pointerdown', onDown, { capture: true })
  for (const ev of ['touchend', 'click', 'keydown']) document.addEventListener(ev, onGesture, { capture: true })
  return () => {
    document.removeEventListener('pointerdown', onDown, { capture: true })
    for (const ev of ['touchend', 'click', 'keydown']) document.removeEventListener(ev, onGesture, { capture: true })
  }
}
