// Sound effects are short WAV files (generated by scripts/make-sounds.mjs) played through <audio> elements.
// Unlike the Web Audio API, media elements keep playing when an iPhone's silent switch is on,
// and they are allowed as soon as the page has had any tap.
import { SOUNDS } from './sounds.generated'

type Name = keyof typeof SOUNDS

let enabled = true
const elements: Partial<Record<Name, HTMLAudioElement>> = {}
/** sounds a real tap asked for while the silent unlock was still running – the unlock must not cut them off */
const wanted = new Set<Name>()

export function setSoundEnabled(on: boolean): void {
  enabled = on
}

function element(name: Name): HTMLAudioElement {
  let a = elements[name]
  if (!a) {
    a = new Audio(SOUNDS[name])
    a.preload = 'auto'
    a.volume = 1
    elements[name] = a
  }
  return a
}

function play(name: Name): Promise<boolean> {
  if (!enabled) return Promise.resolve(false)
  const a = element(name)
  wanted.add(name)
  a.muted = false
  try {
    a.currentTime = 0
  } catch {
    /* not loaded yet – it will start from the beginning anyway */
  }
  return (a.play() ?? Promise.resolve()).then(
    () => true,
    () => false, // blocked until the first tap – later sounds work
  )
}

/**
 * iOS lets a media element play from code only after it has been played once inside a real tap.
 * On the first tap, play every sound silently for an instant so all of them are unlocked.
 */
let primed = false
function prime(): void {
  if (primed) return
  primed = true
  for (const name of Object.keys(SOUNDS) as Name[]) {
    const a = element(name)
    if (!a.paused) continue // already playing a real sound – don't mute it
    wanted.delete(name)
    a.muted = true
    a.play()
      ?.then(() => {
        a.muted = false
        if (wanted.has(name)) return // a real sound started meanwhile – let it play
        a.pause()
        a.currentTime = 0
      })
      .catch(() => {
        a.muted = false
        primed = false // try again on the next tap
      })
  }
}

export const sfx = {
  /** tap for any button */
  tap: () => void play('tap'),
  /** on-screen keyboard key */
  key: () => void play('key'),
  /** right answer: two rising chimes */
  correct: () => void play('correct'),
  /** wrong answer: two falling notes */
  wrong: () => void play('wrong'),
  /** a correct pair while matching */
  match: () => void play('match'),
  /** lesson complete: rising arpeggio with a sparkle */
  complete: () => void play('complete'),
  /** out of hearts */
  fail: () => void play('fail'),
}

/** Plays a sample sound and reports whether the browser allowed it (used by the "test sound" button). */
export function testSound(): Promise<boolean> {
  return play('correct')
}

/** Anything a person would tap or click. Elements can opt out with data-silent (they make their own sound). */
const CLICKABLE =
  'button, a[href], label, summary, select, [role="button"], input[type="checkbox"], input[type="radio"], input[type="date"]'

/** Every tap/click in the app makes a sound. */
export function installClickSounds(): () => void {
  const onDown = (e: Event) => {
    const el = (e.target as Element | null)?.closest?.<HTMLElement>(CLICKABLE)
    if (!el || (el as HTMLButtonElement).disabled || el.dataset.silent !== undefined) return
    if (el.classList.contains('kb-key')) sfx.key()
    else sfx.tap()
  }
  const onGesture = () => prime()
  document.addEventListener('pointerdown', onDown, { capture: true })
  for (const ev of ['touchend', 'click', 'keydown']) document.addEventListener(ev, onGesture, { capture: true })
  return () => {
    document.removeEventListener('pointerdown', onDown, { capture: true })
    for (const ev of ['touchend', 'click', 'keydown']) document.removeEventListener(ev, onGesture, { capture: true })
  }
}
